service: api-sap-mm-id-generator

# Herramientas para trabajo con serverless, en local y en nube
plugins:
  - serverless-offline
  - serverless-dynamodb

provider:
  name: aws
  runtime: nodejs22.x

functions:
  get-new-Id:
    handler: getNewID/handler.getNewID
    events:
      - httpApi:
          path: getNewID
          method: get
  create-new_id:
    handler: createNewId/handler.createNewId
    events:
      - httpApi:
          path: createNewID
          method: POST
#configuracion de puestro del serverless offline y base de datos dynamo
custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002

  dynamodb:
    stages:
      - dev
    start:
      port: 8010
      inMemory: false         # va a requerir un archivo de almacenamiento
      dbPath: .offline-data   # Path donde se guarda el archivo de almacenamiento
      migrate: true

resources:
  Resources:
    devTsIdMasterCounter:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ts_id_master_counter
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
          - AttributeName: priority
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: PriorityIndex 
            KeySchema:
              - AttributeName: priority
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    devTsIdGenerated:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ts_id_generated
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
          - AttributeName: id_generated
            AttributeType: S
          - AttributeName: country
            AttributeType: S
          - AttributeName: date_created
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: idGeneratedIndex
            KeySchema:
              - AttributeName: id_generated
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: dateCreatedIndex
            KeySchema:
              - AttributeName: country
                KeyType: HASH
              - AttributeName: date_created
                KeyType: RANGE
            Projection:
              ProjectionType: ALL